{
	"version": 1572847005,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg1-sheet0.png",
		"images/splay-sheet0.png",
		"images/scredit-sheet0.png",
		"images/sptunjuk-sheet0.png",
		"images/sclose-sheet0.png",
		"images/sprite-sheet0.png",
		"images/spritefont2.png",
		"images/smsc-sheet0.png",
		"images/smsc-sheet1.png",
		"images/sprite6-sheet0.png",
		"images/aswbox-sheet0.png",
		"images/shome-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/quizbox-sheet0.png",
		"images/bg_bar-sheet0.png",
		"images/timerbar.png",
		"images/bgscore-sheet0.png",
		"images/rplybtn-sheet0.png",
		"images/bg-sheet0.png",
		"images/completetxt-sheet0.png",
		"images/windowcopy_-sheet0.png",
		"images/gameovertxt-sheet0.png",
		"images/window-sheet0.png",
		"images/questionguy-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/txtjudul-sheet0.png",
		"images/rbi-sheet0.png",
		"images/questiongu2y-sheet0.png",
		"images/peoplequestions2300x-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/hebat-sheet0.png",
		"images/windowcopy_2-sheet0.png",
		"images/button_-sheet0.png",
		"images/button_2-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/spritefont3.png",
		"images/particles.png",
		"images/firework.png",
		"images/ringsplosion.png",
		"images/sparkpop.png",
		"images/sprtbenar.png",
		"images/sprtbenar1.png",
		"images/sprite8-sheet0.png",
		"images/bestscore.png",
		"images/tombolok-sheet0.png",
		"images/gotoscore-sheet0.png",
		"media/mattoglseby - 2.ogg",
		"media/bensound-littleidea (online-audio-converter.com).ogg",
		"media/game_over (online-audio-converter.com).ogg",
		"media/tepuk_tangan3 (online-audio-converter.com).ogg",
		"media/lagu-nasional-ri-bendera-merah.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"quiz.txt"
	]
}